# Generated by Django 5.1.4 on 2025-01-05 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('language', models.CharField(choices=[('ru', 'RU'), ('en', 'EN'), ('tm', 'TM')], max_length=3)),
                ('icon', models.ImageField(null=True, upload_to='source_icon/')),
            ],
            options={
                'verbose_name_plural': 'Source',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sumary', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='item_photos/')),
                ('url', models.URLField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_news', to='rss_app.source')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
