# Generated by Django 5.1.4 on 2025-01-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
