# Generated by Django 5.1.4 on 2025-01-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_app', '0002_news_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='sumary',
            new_name='summary',
        ),
    ]
