# Generated by Django 5.1.4 on 2025-01-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_app', '0003_rename_sumary_news_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='rss_url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
