# Generated by Django 5.1.4 on 2025-01-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_app', '0004_source_rss_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='rss_url',
        ),
    ]
