# Generated by Django 5.1.4 on 2025-01-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_app', '0008_remove_news_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='guid',
            field=models.CharField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
