# Generated by Django 5.1.4 on 2025-01-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_app', '0009_news_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pubDate',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
