# Generated by Django 5.1.4 on 2025-01-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_app', '0011_news_created_at_news_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pubDate',
            field=models.DateTimeField(null=True),
        ),
    ]
